_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

test_task_photos_api:
    type:     rest
    resource: TestTask\PhotosBundle\Controller\ApiController

test_task_index:
    path: /
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: nelmio_api_doc_index}
