_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

test_task_api_sandbox:
    path: /api/sandbox/{api_method}
    defaults: {_controller: TestTaskPhotosBundle:ApiSandbox:sandbox}
    requirements:
        api_method: delete_photo|delete_tags

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

test_task_photos_api:
    type:     rest
    resource: TestTask\PhotosBundle\Controller\ApiController

