_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

test_task_api_sandbox:
    path: /api/sandbox/{api_method}
    defaults: {_controller: TestTaskPhotosBundle:ApiSandbox:sandbox}
    requirements:
        api_method: post_photo|post_tags_to_photo|delete_photo|delete_tags|get_photos

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

test_task_photos_api:
    type:     rest
    resource: TestTask\PhotosBundle\Controller\ApiController

