<?php

namespace TestTask\PhotosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function getPhotosQb(array $tags = array())
    {
        $qb = $this->createQueryBuilder('photo');

        if ($tags) {
            $qb
                ->join('photo.photoTags', 'photoTags')
                ->andWhere('photoTags.tag IN (:tags)')
                ->setParameter('tags', $tags)
                ->groupBy('photo.id');
        }

        return $qb;
    }
}
